// google-drive/frontend_react/src/components/listers/FileTable.js
import React, { Component } from 'react';
import axios from "axios";
import {Dialog, Grid, IconButton, SpeedDial, SpeedDialIcon, Stack, TablePagination,
    Paper, Table, TableHead ,TableRow, TableContainer, TableBody, TableCell} from "@mui/material";
import { DataGrid } from '@mui/x-data-grid';
import File from "../File";
import CloseIcon from "@mui/icons-material/Close";

class FileTable extends Component {
    constructor(props) {
        super(props);
        this.state = {
            open:false,
            headers:
                [
                    { field: "id", headerName: "id", width:100, sortable: true,type: 'number', headerAlign: 'center',},
                    { field: "name", headerName: "name", width:100, sortable: true,headerAlign: 'center',},
                    { field: "type", headerName: "type", width:100, sortable: true,headerAlign: 'center', },
                    { field: "size", headerName: "size", width:100, sortable: true,type: 'number', },
                    { field: "status", headerName: "status", width:100, sortable: true,headerAlign: 'center', }
                ],
            values: [],
            newValue: {},
            page:1,
            rowsPerPage:5,
            offline:false,
            tick : true,
            editMode: true,
            openDialog : false,
        }
    }

    async componentDidMount () {
        let me = this.props;
        if(this.state.offline){
            if(!me.values) me.values = [];
            return;
        }

        let temp = await axios.get(axios.fixUrl('/files'));
        temp = temp.data._embedded.files.map(obj => {
            return { ...obj, id:obj._links.self.href.split("/")[obj._links.self.href.split("/").length - 1] }
        });
        this.setState({
            ...this.state,
            values: temp,
            newValue: {
                'name': '',
                'type': '',
                'size': 0,
                'status': ''
            }
        });
    }
    descendingComparator = (a, b, orderBy) => {
        if (b[orderBy] < a[orderBy]) {
            return -1;
        }
        if (b[orderBy] > a[orderBy]) {
            return 1;
        }
        return 0;
    }

    getComparator = (order, orderBy) => {
        return order === 'desc'
            ? (a, b) => this.descendingComparator(a, b, orderBy)
            : (a, b) => -this.descendingComparator(a, b, orderBy);
    }

// This method is created for cross-browser compatibility, if you don't
// need to support IE11, you can use Array.prototype.sort() directly
    stableSort = (array, comparator) => {
        const stabilizedThis = array.map((el, index) => [el, index]);
        stabilizedThis.sort((a, b) => {
            const order = comparator(a[0], b[0]);
            if (order !== 0) {
                return order;
            }
            return a[1] - b[1];
        });
        return stabilizedThis.map((el) => el[0]);
    }
    handleChange = ({target}) => {
        console.log("String change", target );
        // this.setState({ newValue: {...this.state.newValue,[target.name]:target.value} });
        this.setState((state) => {
            return {...state, newValue: {...state.newValue,[target.name]:target.value}}
        });
    }
    handleProps = (name, value, index) => {
        if (index >= 0) {
            // console.log(name, value, index, this.state.values);
            this.setState((state) => {
                return {...state, values: this.state.values.map((el,i)=>i===index?{...el, [name]:value}:el)}
            });
        } else {
            this.setState({ [name]: value });
        }
    }
    handleChangePage = (event, newPage) => {
        this.setState({page: newPage});
    }
    handleChangeRowsPerPage = (event) => {
        // this.setRowsPerPage(+event.target.value);
        this.setState({page: 0, rowsPerPage:event.target.value});
    }
    handleClose = (props) => {
        this.setState({ open: false });
    }
    handleOpen = (props) => {
        this.setState({ open: true });
    }
    append = (value) => {
        this.setState({...this.state, tick: false,editMode:true, newValue:{}, values:this.state.values.push(value)});
        this.handleClose();
        // this.$emit('input', this.values);
        // this.$nextTick(function(){
        //     this.tick=true
        // })
    }
    edit = () => {
        this.setState({ editMode: true });
    }

    render() {
        const { headers, values} = this.state;
        return (
            <div>
                <Stack
                    direction="column"
                    justifyContent="flex-start"
                    alignItems="flex-start"
                    sx={{width:'100%'}}
                    spacing={2}
                >
                    <Paper sx={{ width: '100%', overflow: 'hidden', height: 400, }}>
                        <DataGrid
                            rows={values}
                            columns={headers}
                            pageSize={this.state.rowsPerPage}
                            rowsPerPageOptions={[5,10,15]}
                        >
                        </DataGrid>
                    </Paper>
                </Stack>
                <SpeedDial
                    ariaLabel="SpeedDial controlled open example"
                    sx={{ position: 'absolute', bottom: 16, right: 16 }}
                    icon={<SpeedDialIcon />}
                    onClick={this.handleOpen}
                    open={this.state.open}
                />
                <Dialog
                    fullScreen
                    fullWidth={false}
                    maxWidth={false}
                    open={this.state.open}
                    onClose={this.handleClose}
                    // TransitionComponent={Transition}
                >
                    <Grid container sx={{display:'relative'}}>
                        <Grid item xs>
                            {<File offline={this.state.offline} isNew={true} editMode={this.state.editMode} value={this.state.newValue} onChange={this.handleChange}
                                   handleProps={this.handleProps} add={this.append} edit={this.edit} handleClose={this.handleClose} />}
                        </Grid>
                        <Grid>
                            <IconButton
                                edge="start"
                                color="inherit"
                                onClick={this.handleClose}
                                aria-label="close"
                            >
                                <CloseIcon />
                            </IconButton>
                        </Grid>
                    </Grid>
                </Dialog>
            </div>
        );
    }
}
export default FileTable;

// google-drive/frontend_vue/src/components/listers/FileTable.vue
<template>
    <div>
        <v-data-table
                :headers="headers"
                :items="values"
                :items-per-page="5"
                class="elevation-1"
        ></v-data-table>

        <v-col style="margin-bottom:40px;">
            <div class="text-center">
                <v-dialog
                        v-model="openDialog"
                        width="332.5"
                        fullscreen
                        hide-overlay
                        transition="dialog-bottom-transition"
                >
                    <template v-slot:activator="{ on, attrs }">
                        <v-fab-transition>
                            <v-btn
                                    color="blue"
                                    fab
                                    dark
                                    large
                                    style="position:absolute; bottom: 5%; right: 2%; z-index:99"
                                    @click="openDialog=true;"
                            >
                                <v-icon v-bind="attrs" v-on="on">mdi-plus</v-icon>
                            </v-btn>
                        </v-fab-transition>
                    </template>

                    <File :offline="offline" class="video-card" :isNew="true" :editMode="true" v-model="newValue" @add="append" v-if="tick"/>
                
                    <v-btn
                            style="postition:absolute; top:2%; right:2%"
                            @click="closeDialog()"
                            depressed 
                            icon 
                            absolute
                    >
                        <v-icon>mdi-close</v-icon>
                    </v-btn>
                </v-dialog>
            </div>
        </v-col>
    </div>
</template>

<script>
    const axios = require('axios').default;
    import File from '../File.vue';

    export default {
        name: 'FileManager',
        components: {
            File,
        },
        props: {
            offline: Boolean,
            editMode: Boolean,
            isNew: Boolean
        },
        data: () => ({
            values: [],
            headers: 
                [
                    { text: "id", value: "id" },
                    { text: "name", value: "name" },
                    { text: "type", value: "type" },
                    { text: "size", value: "size" },
                    { text: "status", value: "status" },
                ],
            file : [],
            newValue: {},
            tick : true,
            openDialog : false,
        }),
        async created() {
            if(this.offline){
                if(!this.values) this.values = [];
                return;
            }

            var temp = await axios.get(axios.fixUrl('/files'))
            temp.data._embedded.files.map(obj => obj.id=obj._links.self.href.split("/")[obj._links.self.href.split("/").length - 1])
            this.values = temp.data._embedded.files;

            this.newValue = {
                'name': '',
                'type': '',
                'size': 0,
                'status': '',
            }
        },
        methods: {
            closeDialog(){
                this.openDialog = false
            },
            append(value){
                this.tick = false
                this.newValue = {}
                this.values.push(value)
                
                this.$emit('input', this.values);

                this.$nextTick(function(){
                    this.tick=true
                })
            },
        }
    }
</script>
